// src/app/pagination.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Input,
  Output,
  computed,
  input,
} from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'pagination',
  standalone: true,
  imports: [RouterOutlet, CommonModule],
  template: `
    <ul class="pagination">
      <li
        *ngFor="let page of pages()"
        [ngClass]="{ 'page-item': true, active: currentPage() === page }"
        (click)="changePage.emit(page)"
      >
        <span class="page-link">{{ page }}</span>
      </li>
    </ul>
  `,
})
export class PaginationComponent {
  // @Input() currentPage: number = 1;
  // @Input() total: number = 0;
  // @Input() limit: number = 20;
  @Output() changePage = new EventEmitter<number>();

  currentPage = input.required<number>();
  total = input.required<number>();
  limit = input.required<number>();
  pages = computed(() => {
    const pagesCount = Math.ceil(this.total() / this.limit());
    return this.range(1, pagesCount);
  });

  range(start: number, end: number): number[] {
    return [...Array(end - start).keys()].map((el) => el + start);
  }
}

// src/pagination/Pagination.jsx
import { range } from "../utils";

const Pagination = ({ total, limit, currentPage, selectPage }) => {
  const pagesCount = Math.ceil(total / limit);
  const pages = range(1, pagesCount + 1);

  return (
    <ul className="pagination">
      {pages.map((page) => (
        <li
          data-testid="page-container"
          key={page}
          onClick={() => selectPage(page)}
          className={`page-item ${currentPage === page ? "active" : ""}`}
        >
          <span className="page-link">{page}</span>
        </li>
      ))}
    </ul>
  );
};

export default Pagination;
