// src/main/Main.tsx
import classNames from "classnames";
import { Outlet } from "react-router-dom";
import "./main.css";

type MainProps = {
  isLeftSidebarCollapsed: boolean;
  screenWidth: number;
};

const Main = ({ isLeftSidebarCollapsed, screenWidth }: MainProps) => {
  const getSizeClass = () => {
    if (isLeftSidebarCollapsed) {
      return "";
    }
    return screenWidth > 768 ? "body-trimmed" : "body-md-screen";
  };
  const classes = classNames({
    body: true,
    [getSizeClass()]: true,
  });

  return (
    <div className={classes}>
      <Outlet />
    </div>
  );
};

export default Main;

// src/app/main/main.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, input } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-main',
  standalone: true,
  imports: [RouterOutlet, CommonModule],
  templateUrl: './main.component.html',
  styleUrl: './main.component.css',
})
export class MainComponent {
  isLeftSidebarCollapsed = input.required<boolean>();
  screenWidth = input.required<number>();
  sizeClass = computed(() => {
    const isLeftSidebarCollapsed = this.isLeftSidebarCollapsed();
    if (isLeftSidebarCollapsed) {
      return '';
    }
    return this.screenWidth() > 768 ? 'body-trimmed' : 'body-md-screen';
  });
}

<div class="body" [ngClass]="sizeClass()">
  <router-outlet />
</div>
