// src/app/login/login.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  standalone: true,
  imports: [ReactiveFormsModule],
})
export class LogicComponent {
  fb = inject(FormBuilder);
  http = inject(HttpClient);
  router = inject(Router);

  form = this.fb.nonNullable.group({
    email: ['', Validators.required],
    password: ['', Validators.required],
  });
  errorMessage: string | null = null;

  onSubmit(): void {
    console.log('login');
  }
}

<h1>Login</h1>

@if (errorMessage) {
<div>{{ errorMessage }}</div>
}

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <div>
    <input type="text" placeholder="Email" formControlName="email" />
  </div>
  <div>
    <input type="password" placeholder="Password" formControlName="password" />
  </div>
  <div>
    <button type="submit" [disabled]="form.invalid">Sign In</button>
  </div>
</form>

// src/login/Login.jsx
const Login = () => {
  return (
    <div>
      <h1>Login</h1>
      <form>
        <div>
          <input type="text" placeholder="Email" />
        </div>
        <div>
          <input type="password" placeholder="Password" />
        </div>
        <div>
          <button type="submit">Sign In</button>
        </div>
      </form>
    </div>
  );
};

export default Login;
