// src/app/todos/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { TodosService } from 'src/app/todos/services/todos';
import { FilterEnum } from 'src/app/todos/types/filter.enum';

@Component({
  selector: 'app-todos-footer',
  templateUrl: './footer.component.html',
})
export class FooterComponent {
  activeCount$: Observable<number>;
  noTodosClass$: Observable<boolean>;
  itemsLeftText$: Observable<string>;
  filterEnum = FilterEnum;

  constructor(private todosService: TodosService) {
    this.activeCount$ = this.todosService.todos$.pipe(
      map((todos) => todos.filter((todo) => !todo.isCompleted).length)
    );
    this.noTodosClass$ = this.todosService.todos$.pipe(
      map((todos) => todos.length === 0)
    );
    this.itemsLeftText$ = this.activeCount$.pipe(
      map((activeCount) => ` item${activeCount !== 1 ? 's' : ''} left`)
    );
  }

  getSelectedClass(filterName: string) {
    return this.todosService.filter$.pipe(
      map((filter) => filter === filterName)
    );
  }

  changeFilter(event: Event, filterName: FilterEnum): void {
    event.preventDefault();
    this.todosService.changeFilter(filterName);
  }
}

<footer class="footer" [ngClass]="{ hidden: noTodosClass$ | async }">
  <span class="todo-count">
    <strong>{{ activeCount$ | async }}</strong>
    {{ itemsLeftText$ | async }}
  </span>
  <ul class="filters">
    <li>
      <a
        href="/"
        [ngClass]="{ selected: getSelectedClass(filterEnum.all) }"
        (click)="changeFilter($event, filterEnum.all)"
      >
        All
      </a>
    </li>
    <li>
      <a
        href="/"
        [ngClass]="{ selected: getSelectedClass(filterEnum.active) }"
        (click)="changeFilter($event, filterEnum.active)"
      >
        Active
      </a>
    </li>
    <li>
      <a
        href="/"
        [ngClass]="{ selected: getSelectedClass(filterEnum.completed) }"
        (click)="changeFilter($event, filterEnum.completed)"
      >
        Completed
      </a>
    </li>
  </ul>
</footer>

// src/todos/components/Footer.jsx
const Footer = ({ todos, filter }) => {
  const noTodosClass = todos.length === 0 ? "hidden" : "";
  const activeCount = todos.filter((todo) => !todo.isCompleted).length;
  const itemsLeftText = ` item${activeCount !== 1 ? "s" : ""} left`;
  const getSelectedClass = (filterName) => {
    return filter === filterName ? "selected" : "";
  };
  const changeActiveFilter = (event, filterName) => {
    event.preventDefault();
    changeFilter(filterName);
  };

  return (
    <footer className={`footer ${noTodosClass}`} data-testid="footer">
      <span className="todo-count" data-testid="todoCount" data-cy="todoCount">
        <strong>{activeCount}</strong>
        {itemsLeftText}
      </span>
      <ul className="filters">
        <li>
          <a
            href="/"
            data-testid="filterLink"
            data-cy="filterLink"
            className={getSelectedClass("all")}
            onClick={(event) => changeActiveFilter(event, "all")}
          >
            All
          </a>
        </li>
        <li>
          <a
            href="/"
            data-testid="filterLink"
            data-cy="filterLink"
            className={getSelectedClass("active")}
            onClick={(event) => changeActiveFilter(event, "active")}
          >
            Active
          </a>
        </li>
        <li>
          <a
            href="/"
            data-testid="filterLink"
            data-cy="filterLink"
            className={getSelectedClass("completed")}
            onClick={(event) => changeActiveFilter(event, "completed")}
          >
            Completed
          </a>
        </li>
      </ul>
    </footer>
  );
};
export default Footer;
