// src/usersTable/UsersTable.jsx
import "./usersTable.css";
import { useEffect, useState } from "react";

const HeaderCell = ({ column, sorting, sortTable }) => {
  const name = column.charAt(0).toUpperCase() + column.substring(1);
  const isDescSorting = sorting.column === column && sorting.order === "desc";
  const isAscSorting = sorting.column === column && sorting.order === "asc";
  const futureSortingOrder = isDescSorting ? "asc" : "desc";
  return (
    <th
      key={column}
      className="users-table-cell"
      onClick={() => sortTable({ column, order: futureSortingOrder })}
    >
      {name}
      {isDescSorting && <span>▼</span>}
      {isAscSorting && <span>▲</span>}
    </th>
  );
};

const Header = ({ columns, sorting, sortTable }) => {
  return (
    <thead>
      <tr>
        {columns.map((column) => (
          <HeaderCell
            key={column}
            column={column}
            sorting={sorting}
            sortTable={sortTable}
          />
        ))}
      </tr>
    </thead>
  );
};

const Content = ({ entries, columns }) => {
  return (
    <tbody>
      {entries.map((entry) => (
        <tr key={entry.id}>
          {columns.map((column) => (
            <td key={column} className="users-table-cell">
              {entry[column]}
            </td>
          ))}
        </tr>
      ))}
    </tbody>
  );
};

const SearchBar = ({ searchTable }) => {
  const [searchValue, setSearchValue] = useState("");
  const submitForm = (e) => {
    e.preventDefault();
    searchTable(searchValue);
  };
  return (
    <div className="search-bar">
      <form onSubmit={submitForm}>
        <input
          type="text"
          placeholder="Search..."
          value={searchValue}
          onChange={(e) => setSearchValue(e.target.value)}
        />
      </form>
    </div>
  );
};

const UsersTable = () => {
  const columns = ["id", "name", "age"];
  const [users, setUsers] = useState([]);
  const [sorting, setSorting] = useState({ column: "id", order: "asc" });
  const [searchName, setSearchName] = useState("");
  const sortTable = (newSorting) => {
    setSorting(newSorting);
  };
  const searchTable = (searchValue) => {
    setSearchName(searchValue);
  };
  useEffect(() => {
    const url = `http://localhost:3004/users?_sort=${sorting.column}&_order=${sorting.order}&name_like=${searchName}`;
    fetch(url)
      .then((res) => res.json())
      .then((users) => {
        setUsers(users);
      });
  }, [sorting, searchName]);
  return (
    <div>
      <SearchBar searchTable={searchTable} />
      <table className="users-table">
        <Header columns={columns} sortTable={sortTable} sorting={sorting} />
        <Content entries={users} columns={columns} />
      </table>
    </div>
  );
};

export default UsersTable;

// src/app/usersTable/usersTable.component.ts
import { CommonModule, isPlatformServer } from '@angular/common';
import {
  Component,
  Inject,
  OnInit,
  PLATFORM_ID,
  afterNextRender,
  inject,
} from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
// import { makeStateKey, TransferState } from '@angular/platform-browser';
import { UsersService } from './services/users.service';
import { SortingInterface } from './types/sorting.interface';
import { UserInterface } from './types/user.interface';

@Component({
  selector: 'users-table',
  templateUrl: './usersTable.component.html',
  styleUrls: ['./usersTable.component.css'],
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  providers: [UsersService],
})
export class UsersTableComponent implements OnInit {
  usersService = inject(UsersService);
  fb = inject(FormBuilder);
  platformId = inject(PLATFORM_ID);
  columns: Array<keyof UserInterface> = ['id', 'name', 'age'];
  sorting: SortingInterface = {
    column: 'id',
    order: 'asc',
  };
  users: UserInterface[] = [];
  searchValue: string = '';
  searchForm = this.fb.nonNullable.group({
    searchValue: '',
  });

  constructor() {
    afterNextRender(() => {
      console.log(
        'constructor',
        this.platformId,
        localStorage.getItem('token')
      );
    });
  }

  ngOnInit(): void {
    // if (this.transferState.hasKey(makeStateKey('usersTable'))) {
    //   this.users = this.transferState.get(makeStateKey('usersTable'), []);
    // } else {
    this.fetchData();
    // }
  }

  fetchData(): void {
    this.usersService
      .getUsers(this.sorting, this.searchValue)
      .subscribe((users) => {
        // if (isPlatformServer(this.platformId)) {
        //   this.transferState.set<UserInterface[]>(
        //     makeStateKey('usersTable'),
        //     users
        //   );
        // }
        this.users = users;
      });
  }

  capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.substring(1);
  }

  isDescSorting(column: string): boolean {
    return this.sorting.column === column && this.sorting.order === 'desc';
  }

  isAscSorting(column: string): boolean {
    return this.sorting.column === column && this.sorting.order === 'asc';
  }

  sortTable(column: string): void {
    const futureSortingOrder = this.isDescSorting(column) ? 'asc' : 'desc';
    this.sorting = {
      column,
      order: futureSortingOrder,
    };
    this.fetchData();
  }

  onSearchSubmit(): void {
    this.searchValue = this.searchForm.value.searchValue ?? '';
    this.fetchData();
  }
}

<div>
  <div class="search-bar">
    <form [formGroup]="searchForm" (ngSubmit)="onSearchSubmit()">
      <input
        type="text"
        placeholder="Search..."
        formControlName="searchValue"
      />
    </form>
  </div>
  <table class="users-table">
    <thead>
      <tr>
        <th
          *ngFor="let column of columns"
          class="users-table-cell"
          (click)="sortTable(column)"
        >
          {{ capitalize(column) }}
          <span *ngIf="isDescSorting(column)">▼</span>
          <span *ngIf="isAscSorting(column)">▲</span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let user of users">
        <td *ngFor="let column of columns" class="users-table-cell">
          {{ user[column] }}
        </td>
      </tr>
    </tbody>
  </table>
</div>
