// src/app/badTable/badTable.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'bad-table',
  templateUrl: './badTable.component.html',
  styleUrls: ['./badTable.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class BadTable implements OnInit {
  @Input() issues: any;

  selectDeselectAllIsChecked = false;
  numCheckboxesSelected = 0;
  checkedState: any;

  ngOnInit() {
    this.checkedState = new Array(this.issues.length).fill({
      checked: false,
      backgroundColor: '#ffffff',
    });
  }

  getStylesTr(issue: any) {
    return issue.status === 'open' ? 'openIssue' : 'closedIssue';
  }

  onClick(index: any, issue: any) {
    if (issue.status === 'open') {
      this.handleOnChange(index);
    }
  }

  handleOnChange(position: any) {
    const updatedCheckedState = this.checkedState.map(
      (element: any, index: any) => {
        if (position === index) {
          return {
            ...element,
            checked: !element.checked,
            backgroundColor: element.checked ? '#ffffff' : '#eeeeee',
          };
        }
        return element;
      }
    );
    this.checkedState = updatedCheckedState;
    console.log('handleOnChange', this.checkedState, position);
    const totalSelected = updatedCheckedState
      .map((element: any) => element.checked)
      .reduce((sum: any, currentState: any, index: any) => {
        if (currentState) {
          return sum + this.issues[index].value;
        }
        return sum;
      }, 0);
    this.numCheckboxesSelected = totalSelected;
    console.log;
    this.handleIndeterminateCheckbox(totalSelected);
  }

  handleIndeterminateCheckbox(total: any) {
    const indeterminateCheckbox = document.getElementById(
      'custom-checkbox-selectDeselectAll'
    );
    let count = 0;

    this.issues.forEach((element: any) => {
      if (element.status === 'open') {
        count += 1;
      }
    });

    if (total === 0) {
      (indeterminateCheckbox as any).indeterminate = false;
      this.selectDeselectAllIsChecked = false;
    }
    if (total > 0 && total < count) {
      (indeterminateCheckbox as any).indeterminate = true;
      this.selectDeselectAllIsChecked = false;
    }
    if (total === count) {
      (indeterminateCheckbox as any).indeterminate = false;
      this.selectDeselectAllIsChecked = true;
    }
  }

  handleSelectDeselectAll(event: any) {
    let { checked } = event.target;

    const allTrueArray: any = [];
    this.issues.forEach((element: any) => {
      if (element.status === 'open') {
        allTrueArray.push({ checked: true, backgroundColor: '#eeeeee' });
      } else {
        allTrueArray.push({ checked: false, backgroundColor: '#ffffff' });
      }
    });

    const allFalseArray = new Array(this.issues.length).fill({
      checked: false,
      backgroundColor: '#ffffff',
    });
    if (checked) {
      this.checkedState = allTrueArray;
    } else {
      this.checkedState = allFalseArray;
    }

    const totalSelected = (checked ? allTrueArray : allFalseArray)
      .map((element: any) => element.checked)
      .reduce((sum: any, currentState: any, index: any) => {
        if (currentState && this.issues[index].status === 'open') {
          return sum + this.issues[index].value;
        }
        return sum;
      }, 0);
    this.numCheckboxesSelected = totalSelected;
    this.selectDeselectAllIsChecked = !this.selectDeselectAllIsChecked;
  }
}

<table class="table">
  <thead>
    <tr>
      <th>
        <input
          class="checkbox"
          [type]="'checkbox'"
          [id]="'custom-checkbox-selectDeselectAll'"
          [name]="'custom-checkbox-selectDeselectAll'"
          [value]="'custom-checkbox-selectDeselectAll'"
          [checked]="selectDeselectAllIsChecked"
          (change)="handleSelectDeselectAll($event)"
        />
      </th>
      <th class="numChecked">
        <span *ngIf="numCheckboxesSelected"
          >Selected {{ numCheckboxesSelected }}</span
        >
        <span *ngIf="!numCheckboxesSelected">None</span>
      </th>
    </tr>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Message</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <ng-container *ngFor="let issue of issues; index as index">
      <tr class="getStylesTr(issue)" [ngStyle]="checkedState[index]">
        <td>
          <input
            *ngIf="$any(issue).status === 'open'"
            class="checkbox"
            [type]="'checkbox'"
            [id]="'custom-checkbox-' + index"
            [name]="issue.name"
            [value]="issue.name"
            [checked]="checkedState[index].checked"
            (change)="handleOnChange(index)"
          />
          <input
            *ngIf="issue.status !== 'open'"
            class="checkbox"
            [type]="'checkbox'"
            disabled
          />
        </td>
        <td>{{ issue.name }}</td>
        <td>{{ issue.message }}</td>
        <td>
          <span class="openCircle" *ngIf="issue.status === 'open'"></span>
          <span class="resolvedCircle" *ngIf="issue.status !== 'open'"></span>
        </td>
      </tr>
    </ng-container>
  </tbody>
</table>

// src/BadTable.jsx
import { useState } from "react";
import classes from "./Table.module.css";

function BadTable({ issues }) {
  const [checkedState, setCheckedState] = useState(
    new Array(issues.length).fill({
      checked: false,
      backgroundColor: "#ffffff",
    })
  );
  const [selectDeselectAllIsChecked, setSelectDeselectAllIsChecked] =
    useState(false);
  const [numCheckboxesSelected, setNumCheckboxesSelected] = useState(0);

  const handleOnChange = (position) => {
    const updatedCheckedState = checkedState.map((element, index) => {
      if (position === index) {
        return {
          ...element,
          checked: !element.checked,
          backgroundColor: element.checked ? "#ffffff" : "#eeeeee",
        };
      }
      return element;
    });
    setCheckedState(updatedCheckedState);

    const totalSelected = updatedCheckedState
      .map((element) => element.checked)
      .reduce((sum, currentState, index) => {
        if (currentState) {
          return sum + issues[index].value;
        }
        return sum;
      }, 0);
    setNumCheckboxesSelected(totalSelected);

    handleIndeterminateCheckbox(totalSelected);
  };

  const handleIndeterminateCheckbox = (total) => {
    const indeterminateCheckbox = document.getElementById(
      "custom-checkbox-selectDeselectAll"
    );
    let count = 0;

    issues.forEach((element) => {
      if (element.status === "open") {
        count += 1;
      }
    });

    if (total === 0) {
      indeterminateCheckbox.indeterminate = false;
      setSelectDeselectAllIsChecked(false);
    }
    if (total > 0 && total < count) {
      indeterminateCheckbox.indeterminate = true;
      setSelectDeselectAllIsChecked(false);
    }
    if (total === count) {
      indeterminateCheckbox.indeterminate = false;
      setSelectDeselectAllIsChecked(true);
    }
  };

  const handleSelectDeselectAll = (event) => {
    let { checked } = event.target;

    const allTrueArray = [];
    issues.forEach((element) => {
      if (element.status === "open") {
        allTrueArray.push({ checked: true, backgroundColor: "#eeeeee" });
      } else {
        allTrueArray.push({ checked: false, backgroundColor: "#ffffff" });
      }
    });

    const allFalseArray = new Array(issues.length).fill({
      checked: false,
      backgroundColor: "#ffffff",
    });
    checked ? setCheckedState(allTrueArray) : setCheckedState(allFalseArray);

    const totalSelected = (checked ? allTrueArray : allFalseArray)
      .map((element) => element.checked)
      .reduce((sum, currentState, index) => {
        if (currentState && issues[index].status === "open") {
          return sum + issues[index].value;
        }
        return sum;
      }, 0);
    setNumCheckboxesSelected(totalSelected);
    setSelectDeselectAllIsChecked((prevState) => !prevState);
  };

  return (
    <table className={classes.table}>
      <thead>
        <tr>
          <th>
            <input
              className={classes.checkbox}
              type={"checkbox"}
              id={"custom-checkbox-selectDeselectAll"}
              name={"custom-checkbox-selectDeselectAll"}
              value={"custom-checkbox-selectDeselectAll"}
              checked={selectDeselectAllIsChecked}
              onChange={handleSelectDeselectAll}
            />
          </th>
          <th className={classes.numChecked}>
            {numCheckboxesSelected
              ? `Selected ${numCheckboxesSelected}`
              : "None selected"}
          </th>
        </tr>
        <tr>
          <th />
          <th>Name</th>
          <th>Message</th>
          <th>Status</th>
        </tr>
      </thead>

      <tbody>
        {issues.map(({ name, message, status }, index) => {
          let issueIsOpen = status === "open";
          let onClick = issueIsOpen ? () => handleOnChange(index) : null;
          let stylesTr = issueIsOpen
            ? classes.openIssue
            : classes.resolvedIssue;

          return (
            <tr
              className={stylesTr}
              style={checkedState[index]}
              key={index}
              onClick={onClick}
            >
              <td>
                {issueIsOpen ? (
                  <input
                    className={classes.checkbox}
                    type={"checkbox"}
                    id={`custom-checkbox-${index}`}
                    name={name}
                    value={name}
                    checked={checkedState[index].checked}
                    onChange={() => handleOnChange(index)}
                  />
                ) : (
                  <input
                    className={classes.checkbox}
                    type={"checkbox"}
                    disabled
                  />
                )}
              </td>
              <td>{name}</td>
              <td>{message}</td>
              <td>
                {issueIsOpen ? (
                  <span className={classes.greenCircle} />
                ) : (
                  <span className={classes.redCircle} />
                )}
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
}
export default BadTable;
