// src/app/calendar/calendar.component.ts
import {
  Component,
  InputSignal,
  Signal,
  WritableSignal,
  computed,
  input,
  signal,
} from '@angular/core';
import { Meetings } from './meetings.interface';
import { DateTime, Info, Interval } from 'luxon';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'calendar',
  templateUrl: './calendar.component.html',
  styleUrls: ['./calendar.component.css'],
  imports: [CommonModule],
  standalone: true,
})
export class CalendarComponent {
  meetings: InputSignal<Meetings> = input.required();
  today: WritableSignal<DateTime> = signal(DateTime.local());
  activeDay: WritableSignal<DateTime | null> = signal(null);
  activeDayMeetings: Signal<string[]> = computed(() => {
    const activeDay = this.activeDay();
    if (activeDay === null) {
      return [];
    }

    const activeDayISO = activeDay.toISODate();

    if (!activeDayISO) {
      return [];
    }

    return this.meetings()[activeDayISO] ?? [];
  });
  firstDayOfActiveMonth: WritableSignal<DateTime> = signal(
    this.today().startOf('month'),
  );
  weekDays: Signal<string[]> = signal(Info.weekdays('short'));
  daysOfMonth: Signal<DateTime[]> = computed(() => {
    return Interval.fromDateTimes(
      this.firstDayOfActiveMonth().startOf('week'),
      this.firstDayOfActiveMonth().endOf('month').endOf('week'),
    )
      .splitBy({ day: 1 })
      .map((d) => {
        if (d.start === null) {
          throw new Error('Wrong dates');
        }
        return d.start;
      });
  });
  DATE_MED = DateTime.DATE_MED;

  goToPreviousMonth(): void {
    this.firstDayOfActiveMonth.set(
      this.firstDayOfActiveMonth().minus({ month: 1 }),
    );
  }
  goToNextMonth(): void {
    this.firstDayOfActiveMonth.set(
      this.firstDayOfActiveMonth().plus({ month: 1 }),
    );
  }
  goToToday(): void {
    this.firstDayOfActiveMonth.set(this.today().startOf('month'));
  }
}

<div class="calendar-container">
  <div class="calendar">
    <div class="calendar-headline">
      <div class="calendar-headline-month">
        {{ firstDayOfActiveMonth().monthShort }},
        {{ firstDayOfActiveMonth().year }}
      </div>
      <div class="calendar-headline-controls">
        <div (click)="goToPreviousMonth()" class="calendar-headline-control">
          «
        </div>
        <div
          (click)="goToToday()"
          class="calendar-headliner-controls-today calendar-headline-control"
        >
          Today
        </div>
        <div (click)="goToNextMonth()" class="calendar-headline-control">»</div>
      </div>
    </div>

    <div class="calendar-weeks-grid">
      @for (weekDay of weekDays(); track $index) {
        <div class="calendar-weeks-grid-cell">
          {{ weekDay }}
        </div>
      }
    </div>

    <div class="calendar-grid">
      @for (dayOfMonth of daysOfMonth(); track $index) {
        <div
          (click)="activeDay.set(dayOfMonth)"
          [ngClass]="{
            'calendar-grid-cell': true,
            'calendar-grid-cell-inactive':
              dayOfMonth.month !== firstDayOfActiveMonth().month,
            'calendar-grid-cell-active':
              activeDay()?.toISODate() === dayOfMonth.toISODate()
          }"
        >
          {{ dayOfMonth.day }}
        </div>
      }
    </div>
  </div>
  <div class="schedule">
    <div class="schedule-headline">
      @if (activeDay(); as activeDay) {
        <div>{{ activeDay.toLocaleString(DATE_MED) }}</div>
      } @else {
        <div>Please select a day</div>
      }
    </div>
    <div>
      @if (activeDay() && activeDayMeetings().length === 0) {
        <div>No Planned Meetings Today</div>
      }
      @if (activeDay() && activeDayMeetings().length > 0) {
        @for (meeting of activeDayMeetings(); track $index) {
          <div>{{ meeting }}</div>
        }
      }
    </div>
  </div>
</div>

// src/Calendar.jsx
import { DateTime, Info, Interval } from "luxon";
import "./calendar.css";
import { useState } from "react";
import classnames from "classnames";

const Calendar = ({ meetings }) => {
  const today = DateTime.local();
  const [activeDay, setActiveDay] = useState(null);
  const activeDayMeetings = meetings[activeDay?.toISODate()] ?? [];
  const [firstDayOfActiveMonth, setFirstDayOfActiveMonth] = useState(
    today.startOf("month")
  );
  const weekDays = Info.weekdays("short");
  const daysOfMonth = Interval.fromDateTimes(
    firstDayOfActiveMonth.startOf("week"),
    firstDayOfActiveMonth.endOf("month").endOf("week")
  )
    .splitBy({ day: 1 })
    .map((d) => d.start);
  const goToPreviousMonth = () => {
    setFirstDayOfActiveMonth(firstDayOfActiveMonth.minus({ month: 1 }));
  };
  const goToNextMonth = () => {
    setFirstDayOfActiveMonth(firstDayOfActiveMonth.plus({ month: 1 }));
  };
  const goToToday = () => {
    setFirstDayOfActiveMonth(today.startOf("month"));
  };
  return (
    <div className="calendar-container">
      <div className="calendar">
        <div className="calendar-headline">
          <div className="calendar-headline-month">
            {firstDayOfActiveMonth.monthShort}, {firstDayOfActiveMonth.year}
          </div>
          <div className="calendar-headline-controls">
            <div
              onClick={() => goToPreviousMonth()}
              className="calendar-headline-control"
            >
              «
            </div>
            <div
              onClick={() => goToToday()}
              className="calendar-headliner-controls-today calendar-headline-control"
            >
              Today
            </div>
            <div
              onClick={() => goToNextMonth()}
              className="calendar-headline-control"
            >
              »
            </div>
          </div>
        </div>
        <div className="calendar-weeks-grid">
          {weekDays.map((weekDay, weekDayIndex) => (
            <div key={weekDayIndex} className="calendar-weeks-grid-cell">
              {weekDay}
            </div>
          ))}
        </div>

        <div className="calendar-grid">
          {daysOfMonth.map((dayOfMonth, dayOfMonthIndex) => (
            <div
              key={dayOfMonthIndex}
              onClick={() => setActiveDay(dayOfMonth)}
              className={classnames({
                "calendar-grid-cell": true,
                "calendar-grid-cell-inactive":
                  dayOfMonth.month !== firstDayOfActiveMonth.month,
                "calendar-grid-cell-active":
                  activeDay?.toISODate() === dayOfMonth.toISODate(),
              })}
            >
              {dayOfMonth.day}
            </div>
          ))}
        </div>
      </div>
      <div className="schedule">
        <div className="schedule-headline">
          {activeDay === null && <div>Please select a day</div>}
          {activeDay && (
            <div>{activeDay.toLocaleString(DateTime.DATE_MED)}</div>
          )}
        </div>
        <div>
          {activeDay && activeDayMeetings.length === 0 && (
            <div>No Planned Meetings Today</div>
          )}
          {activeDay && activeDayMeetings.length > 0 && (
            <>
              {activeDayMeetings.map((meeting, meetingIndex) => (
                <div key={meetingIndex}>{meeting}</div>
              ))}
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default Calendar;
