// src/app/goodTable/goodTable.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnInit, computed, signal } from '@angular/core';
import { IssueInterface } from './issue.interface';

interface IssueEntriesInterface {
  [key: string]: { isSelected: boolean };
}

@Component({
  selector: 'good-table',
  templateUrl: './goodTable.component.html',
  styleUrls: ['./goodTable.component.css'],
  standalone: true,
  imports: [CommonModule],
})
export class GoodTable implements OnInit {
  @Input({ required: true }) issues!: IssueInterface[];

  issuesSig = signal<IssueInterface[]>([]);
  issueEntriesSig = signal<IssueEntriesInterface>({});
  totalSelectedSig = computed(
    () =>
      Object.values(this.issueEntriesSig()).filter(
        (issueData) => issueData.isSelected
      ).length
  );
  indeterminateSig = computed(() => {
    const totalOpenedIssues = this.issuesSig().filter(
      (issue) => issue.status === 'open'
    ).length;
    return (
      this.totalSelectedSig() < totalOpenedIssues && this.totalSelectedSig() > 0
    );
  });

  ngOnInit() {
    this.issuesSig.set(this.issues);
    this.issueEntriesSig.set(this.convertIssuesToEntries(this.issues, false));
  }

  convertIssuesToEntries(
    issues: IssueInterface[],
    isSelected: boolean
  ): IssueEntriesInterface {
    const entries = issues.map((issue) => [
      issue.id,
      { isSelected: issue.status === 'open' ? isSelected : false },
    ]);
    return Object.fromEntries(entries);
  }

  selectRow(issueId: string): void {
    const updatedIssueEntry = {
      ...this.issueEntriesSig()[issueId],
      isSelected: !this.issueEntriesSig()[issueId].isSelected,
    };
    const updatedIssueEntries = {
      ...this.issueEntriesSig(),
      [issueId]: updatedIssueEntry,
    };
    this.issueEntriesSig.set(updatedIssueEntries);
  }

  selectAll(event: Event): void {
    const target = event.target as HTMLInputElement;
    const updatedIssueEntries = this.convertIssuesToEntries(
      this.issuesSig(),
      target.checked
    );
    this.issueEntriesSig.set(updatedIssueEntries);
  }
}

<table class="table">
  <thead>
    <tr>
      <th>
        <input
          class="checkbox"
          type="checkbox"
          [indeterminate]="indeterminateSig()"
          [checked]="totalSelectedSig()"
          (change)="selectAll($event)"
        />
      </th>
      <th class="numChecked">
        <span *ngIf="totalSelectedSig() > 0"
          >Selected {{ totalSelectedSig() }}</span
        >
        <span *ngIf="totalSelectedSig() === 0">None</span>
      </th>
    </tr>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Message</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <ng-container *ngFor="let issue of issuesSig()">
      <tr
        [ngClass]="{
          openIssue: issue.status === 'open',
          resolvedIssue: issue.status === 'resolved'
        }"
        [ngStyle]="{
          backgroundColor: issueEntriesSig()[issue.id].isSelected
            ? '#eeeeee'
            : '#ffffff'
        }"
        (click)="selectRow(issue.id)"
      >
        <td>
          <input
            class="checkbox"
            type="checkbox"
            [checked]="issueEntriesSig()[issue.id].isSelected"
          />
        </td>
        <td>{{ issue.name }}</td>
        <td>{{ issue.message }}</td>
        <td>
          <span
            [ngClass]="{
              openCircle: issue.status === 'open',
              resolvedCircle: issue.status === 'resolved'
            }"
          ></span>
        </td>
      </tr>
    </ng-container>
  </tbody>
</table>

// src/GoodTable.jsx
import { useEffect, useRef, useState } from "react";
import classes from "./Table.module.css";

const GoodTable = ({ issues }) => {
  const convertIssuesToEntries = (isSelected) => {
    const entries = issues.map((issue) => {
      return [
        issue.id,
        { isSelected: issue.status === "open" ? isSelected : false },
      ];
    });
    return Object.fromEntries(entries);
  };
  const [issueEntries, setIssueEntries] = useState(() =>
    convertIssuesToEntries(false)
  );
  const totalSelected = Object.values(issueEntries).filter(
    (issueData) => issueData.isSelected
  ).length;
  const selectAllRef = useRef();
  const selectRow = (issueId) => {
    const updatedIssueEntry = {
      ...issueEntries[issueId],
      isSelected: !issueEntries[issueId].isSelected,
    };
    const updatedIssueEntries = {
      ...issueEntries,
      [issueId]: updatedIssueEntry,
    };
    setIssueEntries(updatedIssueEntries);
  };

  const selectAll = (event) => {
    const updatedIssueEntries = convertIssuesToEntries(event.target.checked);
    setIssueEntries(updatedIssueEntries);
  };

  useEffect(() => {
    const totalOpenedIssues = issues.filter(
      (issue) => issue.status === "open"
    ).length;
    const indeterminate =
      totalSelected < totalOpenedIssues && totalSelected > 0;
    selectAllRef.current.indeterminate = indeterminate;
  }, [issues, totalSelected]);

  return (
    <table className={classes.table}>
      <thead>
        <tr>
          <th>
            <input
              className={classes.checkbox}
              type="checkbox"
              ref={selectAllRef}
              checked={totalSelected}
              onChange={selectAll}
            />
          </th>
          <th className={classes.numChecked}>
            {totalSelected ? `Selected ${totalSelected}` : "None selected"}
          </th>
        </tr>
        <tr>
          <th />
          <th>Name</th>
          <th>Message</th>
          <th>Status</th>
        </tr>
      </thead>

      <tbody>
        {issues.map((issue) => {
          const isOpenedIssue = issue.status === "open";
          const rowClass = isOpenedIssue
            ? classes.openIssue
            : classes.resolvedIssue;
          const statusClass = isOpenedIssue
            ? classes.greenCircle
            : classes.redCircle;
          const backgroundColor = issueEntries[issue.id].isSelected
            ? "#eeeeee"
            : "#ffffff";

          return (
            <tr
              className={rowClass}
              style={{ backgroundColor }}
              key={issue.id}
              onClick={() => selectRow(issue.id)}
            >
              <td>
                <input
                  className={classes.checkbox}
                  type="checkbox"
                  readOnly
                  checked={issueEntries[issue.id].isSelected}
                  disabled={isOpenedIssue}
                />
              </td>
              <td>{issue.name}</td>
              <td>{issue.message}</td>
              <td>
                <span className={statusClass} />
              </td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};
export default GoodTable;
