// src/register/Register.jsx
import { useState } from "react";
import { useDispatch } from "react-redux";
import { registerUser } from "../store/reducers/auth";

const Register = () => {
  const dispatch = useDispatch();
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const onSubmit = (e) => {
    e.preventDefault();
    console.log("onSubmit", username, email, password);
    dispatch(registerUser({ username, email, password }));
  };
  return (
    <div>
      <h1>Register</h1>
      <form onSubmit={onSubmit}>
        <div>
          <input
            type="text"
            placeholder="Username"
            onChange={(e) => setUsername(e.target.value)}
          />
        </div>

        <div>
          <input
            type="text"
            placeholder="Email"
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>
        <div>
          <input
            type="password"
            placeholder="Password"
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>
        <div>
          <button type="submit">Sign Up</button>
        </div>
      </form>
    </div>
  );
};

export default Register;

// src/app/register/register.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  standalone: true,
  imports: [ReactiveFormsModule],
})
export class RegisterComponent {
  fb = inject(FormBuilder);
  http = inject(HttpClient);
  router = inject(Router);

  form = this.fb.nonNullable.group({
    username: ['', Validators.required],
    email: ['', Validators.required],
    password: ['', Validators.required],
  });
  errorMessage: string | null = null;

  onSubmit(): void {
    console.log('register');
  }
}

<h1>Register</h1>

@if (errorMessage) {
<div>{{ errorMessage }}</div>
}

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <div>
    <input type="text" placeholder="Username" formControlName="username" />
  </div>
  <div>
    <input type="text" placeholder="Email" formControlName="email" />
  </div>
  <div>
    <input type="password" placeholder="Password" formControlName="password" />
  </div>
  <div>
    <button type="submit" [disabled]="form.invalid">Sign Up</button>
  </div>
</form>
