// src/views/UsersList.vue
<template>
  <div>
    <input type="text" v-model="newUserName" />
    <button @click="addUser()">Add user</button>
    <div v-for="user in users" :key="user.id" class="user">
      {{ user.name }} <span @click="removeUser(user.id)">Remove</span>
    </div>
    <a :href="url">Some url</a>
  </div>
</template>

<script>
export default {
  name: "UsersList",
  data() {
    return {
      users: [
        {
          id: "1",
          name: "User 1",
          age: 20,
        },
        {
          id: "2",
          name: "User 2",
          age: 25,
        },

        {
          id: "3",
          name: "User 3",
          age: 30,
        },
      ],
      newUserName: "",
      url: "https://google.com",
    };
  },
  methods: {
    removeUser(id) {
      this.users = this.users.filter((user) => user.id !== id);
    },
    addUser() {
      const uniqueId = Math.random().toString(16);
      const newUser = {
        id: uniqueId,
        name: this.newUserName,
        age: 30,
      };
      this.users.push(newUser);
    },
  },
};
</script>

<style scoped>
.user {
  font-size: 18px;
  border-bottom: 1px solid grey;
  padding: 10px;
  display: flex;
  justify-content: space-between;
}
</style>

// src/app/usersList/usersList.component.ts
import {Component} from '@angular/core'

@Component({
  selector: 'app-users-list',
  templateUrl: './usersList.component.html'
})
export class UsersListComponent {
  newUserName: string = ''
  users = [
    {
      id: '1',
      name: 'Jack',
      age: 21
    },
    {
      id: '2',
      name: 'John',
      age: 25
    },

    {
      id: '3',
      name: 'Sam',
      age: 29
    }
  ]

  removeUser(id: string): void {
    this.users = this.users.filter(user => user.id !== id)
  }

  setNewUserName(userName: string): void {
    this.newUserName = userName
  }

  addUser(): void {
    const uniqueId = Math.random().toString(16)
    const newUser = {
      id: uniqueId,
      name: this.newUserName,
      age: 30
    }
    this.users.push(newUser)
    this.newUserName = ''
  }
}

<input
  type="text"
  (change)="setNewUserName($event.target.value)"
  [value]="newUserName"
/>
<button (click)="addUser()">Add user</button>
<div *ngFor="let user of users">
  {{ user.name }} is {{ user.age }} years old
  <span (click)="removeUser(user.id)">Remove</span>
</div>
